# Generated by Django 4.2.6 on 2023-10-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=50)),
                ('vessel_imo', models.IntegerField(blank=True, null=True)),
                ('vessel_rotation', models.TextField(blank=True, null=True)),
                ('vessel_information', models.TextField(blank=True, null=True)),
                ('transit_time', models.IntegerField(blank=True, null=True)),
                ('loading_port', models.CharField(blank=True, max_length=50, null=True)),
                ('anchor_loading_port', models.DateField(blank=True, null=True)),
                ('eta_loading_port', models.DateField(blank=True, null=True)),
                ('etb_loading_port', models.DateField(blank=True, null=True)),
                ('ata_loading_port', models.DateField(blank=True, null=True)),
                ('atb_loading_port', models.DateField(blank=True, null=True)),
                ('etd_loading_port', models.DateField(blank=True, null=True)),
                ('atd_loading_port', models.DateField(blank=True, null=True)),
                ('discharge_port', models.CharField(blank=True, max_length=50, null=True)),
                ('eta_discharge_port', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
