# Generated by Django 4.2.6 on 2023-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0004_rename_discharge_port_vessel_discharge_port_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='discharge_port_name',
            new_name='discharge_port',
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='loading_port_name',
            new_name='loading_port',
        ),
        migrations.AddField(
            model_name='dischargeport',
            name='assigned_vessel_pod',
            field=models.ManyToManyField(blank=True, to='Vessel.vessel'),
        ),
        migrations.AddField(
            model_name='loadingport',
            name='assigned_vessel_pol',
            field=models.ManyToManyField(blank=True, to='Vessel.vessel'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='assigned_agent',
            field=models.ManyToManyField(blank=True, to='Vessel.vesselagent'),
        ),
    ]
