# Generated by Django 4.2.6 on 2023-12-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0005_rename_discharge_port_name_vessel_discharge_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargeport',
            name='assigned_vessel_pod',
        ),
        migrations.RemoveField(
            model_name='loadingport',
            name='assigned_vessel_pol',
        ),
        migrations.AddField(
            model_name='dischargeport',
            name='assigned_vessel_pod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vessel.vessel'),
        ),
        migrations.AddField(
            model_name='loadingport',
            name='assigned_vessel_pol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vessel.vessel'),
        ),
    ]
