# Generated by Django 4.2.6 on 2023-12-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0007_alter_vessel_discharge_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselagent',
            name='assigned_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vessel.vessel'),
        ),
    ]
