# Generated by Django 4.2.6 on 2023-12-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0008_vesselagent_assigned_vessel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='assigned_agent',
        ),
        migrations.AddField(
            model_name='vessel',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vessel.vesselagent'),
        ),
    ]
