# Generated by Django 4.2.6 on 2023-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0009_remove_vessel_assigned_agent_vessel_assigned_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='assigned_agent',
        ),
        migrations.AddField(
            model_name='vessel',
            name='assigned_agent',
            field=models.ManyToManyField(blank=True, to='Vessel.vesselagent'),
        ),
    ]
