# Generated by Django 4.2.6 on 2023-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vessel', '0010_remove_vessel_assigned_agent_vessel_assigned_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselagent',
            name='vessel_agent_address',
        ),
        migrations.RemoveField(
            model_name='vesselagent',
            name='vessel_agent_phone',
        ),
        migrations.RemoveField(
            model_name='vesselagent',
            name='vessel_agent_pic',
        ),
        migrations.AddField(
            model_name='vesselagent',
            name='vessel_agent_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
